---
title: "Coding 2 - Assignment 1: Scraping ESPN for NFL Player Statistics "
author: "Bruno Helmeczy"
date: "23/11/2020"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
---


## Function 2 Get game stats for best X Number of Players 



```{r}
# Scraping NFL Statistics from ESPN.com

GetTopNFLPlayersYTD <-  function(Playtype, top_x_players, year = 2020) {
  
# Check for required Packages
  if(!require(rvest)) install.packages("rvest", repos = "http://cran.us.r-project.org")
  if(!require(data.table)) install.packages("data.table", repos = "http://cran.us.r-project.org")
  if(!require(dplyr)) install.packages("dplyr", repos = "http://cran.us.r-project.org")
  if(!require(stringr)) install.packages("stringr", repos = "http://cran.us.r-project.org")
 
# Load Required Packages 
    library(rvest)
    library(data.table)
    library(dplyr)
    library(stringr)
  
  Stattype <- c("Passing","Rushing","Receiving")
  
# Check if Valid PlayType is inputed -> Return Error if inValid
  if (is.na(Stattype[grep(tolower(Playtype),tolower(Stattype))])) {
    print(paste0("ERROR: Choose from: '", 
                 Stattype[1],"' or '", 
                 Stattype[2],"' or '", 
                 Stattype[3], "'" ))
    
  } else {
  myurl <- paste0('https://www.espn.com/nfl/stats/player/_/stat/',
                  tolower(Stattype[grep(tolower(Playtype),tolower(Stattype))])
                  ,'/season/',year,'/seasontype/2')
  
  print(paste0("Finding YTD ", Stattype[grep(tolower(Playtype),tolower(Stattype))]
               , " data from ", year ))
  
# Getting Table of top players year-to-date
  TableBox <- read_html(myurl) %>% html_nodes('.Table2__title--remove-capitalization')
  
# TableBox has 2 html_nodes, Table--align-right (Statistics) 
                        #  & Table--fixed-left (Links)
  TL <- TableBox %>% html_nodes('.Table--align-right') %>% html_table()

# TL = Temporary list = PlayerNames, Rank, Stats
# TL[[1]] = Players Names & Rank / TL[[2]] = Statistics
  TL <- as.data.frame(cbind(TL[[1]],TL[[2]]))

# Getting Correct PlayerLinks  
  PlayerList  <- TableBox %>% html_nodes('.Table--fixed-left') %>% html_table()
  PlayerLinks <- TableBox %>% html_nodes('.Table--fixed-left') %>% 
    html_nodes('.AnchorLink') %>% html_attr('href')
  
# 1) Add "gamelog/_/" to access ALL games
  PlayerLinks <- unlist(lapply(PlayerLinks, function(x) {
    paste0( unlist(strsplit(x, '_/', fixed = T ))[1],"gamelog/_/",
            unlist(strsplit(x, '_/', fixed = T ))[2])
  }))

# 2) Remove player name from link - only 'id/ Nr.s' needed
  PlayerLinks <- unlist(lapply(PlayerLinks, function(x) {
    str_split(x,str_split_fixed(x,"/", n = 10)[,10])[1]
  }))

# 3) Remove empty strings from end of each link
  PlayerLinks <- PlayerLinks[ PlayerLinks != ""] 
  
# 4) Add replace 'type/' with 'type/nfl/year/' + chosen year
  PlayerLinks <- unlist(lapply(PlayerLinks, function(x) {
    paste0( unlist(strsplit(x, 'type/', fixed = T ))[1],"type/nfl/year/", year)
  }))
  
# 5) Attach corrected Links to Players
  PlayerLinkList <- cbind(PlayerList[[1]],PlayerLinks)
  
# Join PlayerLinklist to TL w left_join - based on ranking & Name
  TL_w_Links <- TL %>% left_join(PlayerLinkList, by = c("RK", "Name"))
  TL_w_Links <- TL_w_Links[1:top_x_players,]

# Show for which players per game statistics is being loaded
  print(paste0("The top ",top_x_players, " ",
               Stattype[grep(tolower(Playtype),tolower(Stattype))],
               " players in ", year, " are:"))
  print(cbind(TL_w_Links$Name[1:top_x_players]))

  print(TL[1:top_x_players,])

# Create Empty dataframe to fill with per game statistics
  df_final <- data.frame()

for (i in 1:top_x_players)    {
  print(paste0("Getting game statistics data for ", TL_w_Links$Name[i] ))
  
  x <- read_html(TL_w_Links$PlayerLinks[i])
  listofTables <- x %>% html_nodes('.Table--align-right') %>% html_table()
    
# Getting game links
  ID_if_game_link <- x %>% html_nodes('.Table--align-right') %>% 
    html_nodes('.AnchorLink') %>% html_attr('data-game-link') 
  GameLink <- x %>% html_nodes('.Table--align-right') %>%  
    html_nodes('.AnchorLink') %>% html_attr('href') 
  
  GameLink <- as.data.frame(cbind(ID_if_game_link,GameLink)) %>% 
    filter(!is.na(ID_if_game_link) ) %>% select(GameLink)
  
# Selecting Correct element from listofTables
    # In previous years, if player was in playoffs, listofTables has multiple elements
  # Has columns named as year + Regular Season
  # Loop through all list elements
  # Correct list has "Regular" in list element j's column names
  # If found, replace 1st element with correct list
  for (j in 1:(length(listofTables))) {
    if (length(grep("Regular",colnames(listofTables[[j]]))) > 0 ) {
      listofTables[[1]] <- listofTables[[j]]
      next()
    } 
  }
  
# Select 1st elemnt from listofTables as Stats
  # Subset to Game ID variables & only chosen PlayType
  Stats <- listofTables[[1]]
  Stats <- cbind(Stats[colnames(Stats) == paste0(year ," Regular Season")], 
                 Stats[colnames(Stats) == Stattype[grep(tolower(Playtype),tolower(Stattype))]])

# Re-Setting correct Column Names - Statistics' names in 1st Row
  colnames(Stats) <- Stats[1,]
  
# Removing incorrect Rows: 1st = Column Names ; Last = Year-To-Date Stats
  Stats <- Stats[2:(length(Stats[,1])-1),]

# Subsetting gamelinks to only Regular Season games - Playoff games are located on top
  GameLink <- GameLink[((length(GameLink[,1]))-(length(Stats[,1]))+1):(length(GameLink[,1])),]
  
# Creating a dataframe of Players' Name , Stats per game & Links to each game
  df <- data.frame(Player = TL_w_Links$Name[i], Stats, GameLink)
  
# Adding current players pergame stats to final dataframe
  df_final <- rbind(df_final,df)
}
print(paste0("Returning per game ", 
             Stattype[grep(tolower(Playtype),tolower(Stattype))],
             " statistics for: "))
print(unique(df_final$Player))

write.csv(df_final, paste0("Top_",top_x_players
                           ,"_NFL_",Stattype[grep(tolower(Playtype),tolower(Stattype))],
                           "_Players_Game_Stats_",year,".csv"))
saveRDS(df_final, paste0("Top_", top_x_players,
                         "_NFL_",Stattype[grep(tolower(Playtype),tolower(Stattype))],
                         "_Players_Game_Stats_",year,".rds"))


return(df_final)
  }
}

```


```{r}
# Scraping NFL Statistics from ESPN.com

GetTopNFLPlayersYTD('Pass', 3)
GetTopNFLPlayersYTD('Rush', 3)
GetTopNFLPlayersYTD('Rec', 3)

GetTopNFLPlayersYTD('Pass', 3, 2019)

```

